
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://aa1tmu4k8hmyfpl.cqqcaenuxmfu.ap-south-1.rds.amazonaws.com:3306/ravidb?allowPublicKeyRetrieval=true&useSSL=false
    username: ravidb
    password: raviroot
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

server:
  port: 5000
